config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root 'users#index'
  # get '/users', to: 'users#index'
  # get "/users/:user_id", to: "users#show"
  # get "/users/:user_id/posts", to: "posts#index"
  # get "/users/:user_id/posts/:post_id", to: "posts#show"
  # get '/login', to: 'pages#login'

  
  # REFACTORED
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :new, :create] do
        resources :comments, only: [:new, :create]
        resources :likes, only: [:create]
      end
    end
    get '/login', to: 'pages#login'
    root "users#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_post_comment_counter
  after_destroy :decrement_post_comment_counter

  validates :text, presence: true, length: { minimum: 3, maximum: 250,
                                             too_long: '%<count>s characters is the maximum allowed',
                                             too_short: '%<count>s characters is the minimum allowed' }

  def update_post_comment_counter
    post.increment!(:comments_counter)
  end

  def decrement_post_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  belongs_to :post, counter_cache: :likes_counter

  after_save :update_post_like_counter
  after_destroy :decrement_post_like_counter

  def update_post_like_counter
    post.increment!(:likes_counter)
  end

  def decrement_post_like_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_user_post_counter
  after_destroy :decrease_user_post_counter

  validates :title, presence: true, length: { minimum: 5, maximum: 250,
                                              too_long: '%<count>s characters is the maximum allowed' }
  validates :comments_counter, numericality: { only_integer: true },
                               comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def update_user_post_counter
    author.increment!(:posts_counter)
  end

  def decrease_user_post_counter
    author.decrement!(:posts_counter)
  end

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 50,
                                             too_long: '%<count>s characters is the maximum allowed' }
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def most_three_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  def current_user
    @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = @current_user.comments.new(comment_params)
    @comment[:post_id] = params[:post_id]

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new; end

  def create
    @post = Post.find(params[:post_id])
    @like = @current_user.likes.new(post_id: @post.id)
    @like.author = @current_user
    if @like.save
      redirect_to user_post_path(@current_user, @post)
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login; end

  def about
    # userArr = User.all
    @message = ['Number 1', 'number 2', 'number 3']
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = @current_user.posts.new
  end

  def create
    @post = @current_user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(@current_user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model:[@current_user, @post, Comment.new], url:user_post_comments_path(@current_user, @post) do |form| %>
  <div class="comment_form">
    <div>
      <%= form.label :comment%><br>
      <%= form.text_area :text, class:'comment_input' %>
      <% form.object.errors.full_messages_for(:text).each do |message|%>
      <div><%= message %></div>
      <%end%>
    </div>
    <br>
    <%= form.submit class:'post_button' %>
  </div>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer-container row">
        <p>
            Build with 🧡 By 
            <a
            href="https://github.com/serengia"
            target="_blank"
            rel="noreferrer"
            >
            James Serengia (GitHub)
            </a>
        </p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
<div class="header-container row">
  <ul class="nav-links">
<li class="nav-link"><%= link_to "Home", root_path%> </li>
<li class="nav-link"><%= link_to "users", users_path%> </li>
<li class="nav-link"><%= link_to "login", login_path%> </li>
</ul>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogPostgres</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model:[@user, @post, Like.new], url:user_post_likes_path(User.find(params[:user_id]), @post) do |form| %>
  <div class="like_form">
    <%= form.submit "Like", class:'post_button' %>
  </div>
<%end%>

app/views/pages/about.html.erb
About page
<% @message.each do |m| %>
 <h1><%= m %></h1>
<%end%>

app/views/pages/login.html.erb
<h1>Login page</h1>

app/views/posts/_form.html.erb
<main class="add-post-page">
   <div class="row">
   <h3> Add New Post </h3>
     <%= form_with model: [@current_user, @current_user.posts.build] do |form| %>
<div class="post_form">

  <div>
  <%= form.label :title  %>
  <%= form.text_field :title, class:'post_title'%>
  <% form.object.errors.full_messages_for(:title).each do |message|%>
  <div><%= message %></div>
  <%end%>
</div>

 <div>
   <%= form.label :text%>
    <%= form.text_area :text, class:'post_text'%>
    <% form.object.errors.full_messages_for(:text).each do |message|%>
    <div><%= message %></div>
    <%end%>
 </div>
 
 <div class="create-new-btn-wrapper">
    <%= form.submit "Create Post", class:"post_button"%>
 </div>
</div>
<%end%>
   </div>
</main>

app/views/posts/index.html.erb
<main class="posts-page">
  <div class="row">
   <%= render partial: "shared/user_card", locals: {u: @user}%>
   <% @posts.each do |p|%>
        <%= render partial: "shared/post_body", locals: {p:p} %>
        <div class="comments-wrapper">
          <%if !p.five_most_recent_comments.empty?%>
              <%= render partial: "shared/comments", locals: {comments: p.five_most_recent_comments}%>
          <%end%>
        </div>
   <%end%>

  </div>

</main>

app/views/posts/new.html.erb
<%= render "form", post:@post%>

app/views/posts/show.html.erb
<div class="single-post-page">
  <div class="row">
    <%= render partial: "shared/post_body"%>
  
    <% if  !@post&.comments.empty?%>
    <div class ="comments_wrapper">
       <% @post.comments.each do |comment| %>
       <%= render partial: 'shared/comments', locals: { c: comment } %>
       <% end %>

       <%end%>
    <div class="comment_like_holder">
     <div class= "comment_form_holder">
       <h3>Leave a comment</h3>
      <%= render 'comments/form', comment: @comment %>
      </div>

       <div class="like_form_holder">
        <h3>Like this post</h3>
        <%= render 'likes/form', like: @like %>
        </div>
      </div>
    </div>
    
</div>

app/views/shared/_comments.html.erb
<div class="comments">
  <%comments.each do |c|%>
    <p class="comment"><span>Username: <%= c.author.name%></span>
    <span>Comment: <%= c.text%></span></p>
  <%end%>
</div>

app/views/shared/_post_body.html.erb
<div class="post-body">
  <div>
    <h2><%=p.title%> <span class="by">by</span><span class="username">Username</span> </h2>
    <p class="commets-and-likes">
        <span>Comments: <%= p.comments_counter%></span>
        <span>Likes: <%= p.likes_counter%></span>
    </p>
  </div>
  <div class="content">
     <p><%= p.text%></p>
  </div>
</div>

app/views/shared/_post_card.html.erb
 <div class="post">
     <h2 class="title"><%= p.title%></h2>
     <p class="preview"><%= p.text%></p>
     <p class="comments-and-likes">
     <span>Comments: <%= p.comments_counter%> </span>
     <span>Likes: <%= p.likes_counter%> </span>
     </p>
   </div>

app/views/shared/_user_card.html.erb
<div class="user-card">
    <div class="image-wrapper">
        <img src="<%= asset_path("user-placeholder.png") %>" class="img"  alt="<%= u.name%>">
    </div>
    <div class="content">
        <h2><%= link_to u.name, "/users/#{u.id}"%></h2>
        <p>No of Posts: <%= u.posts_counter%></p>
    </div>
</div>

app/views/users/index.html.erb
<main class="home">
<div class="users-list-wrapper row">
<h1 class="heading">Users list page</h1>
<% @users.each do |u|%>
 <%= render partial: "shared/user_card", locals: {u:u}%>
<% end %>
<div class="create-new-btn-wrapper">
<%= link_to "Create new post", new_user_post_path(@current_user)%>
</div>
</div>
</main>

 

app/views/users/show.html.erb
<div class="user-details-page">
<div class="row">
  <div class="user-header">
     <%= render partial: "shared/user_card", locals: {u: @user}%>
  </div>

  <div class="user-bio">
     <h2>User bio</h2>
    <p><%= @user.bio%></p>
  </div>
   
   <%@posts.each do |p|%>
      <%= render partial: "shared/post_card", locals: {p:p}%>
   <%end%>

   <div class="button-wrapper">
   <%= link_to "See all posts", user_posts_path(@user) %>
   </div>
   
</div>
</div>